// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZL5IPcRK_I9mp45X1dbPkCXZnnA7K19E',
    appId: '1:481730324850:web:04cd78dab84a53a03ed5eb',
    messagingSenderId: '481730324850',
    projectId: 'groupflow-dd0d4',
    authDomain: 'groupflow-dd0d4.firebaseapp.com',
    storageBucket: 'groupflow-dd0d4.firebasestorage.app',
    measurementId: 'G-JXTQ6Z8WYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoeqa8vdR-LQgfKtaIM_bAAUEzQvDSlqw',
    appId: '1:481730324850:android:083a33fa2b8195e93ed5eb',
    messagingSenderId: '481730324850',
    projectId: 'groupflow-dd0d4',
    storageBucket: 'groupflow-dd0d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI82E_0HdOz-EFgC05Ugj00tVgkY6nXr8',
    appId: '1:481730324850:ios:4914f9dce55945893ed5eb',
    messagingSenderId: '481730324850',
    projectId: 'groupflow-dd0d4',
    storageBucket: 'groupflow-dd0d4.firebasestorage.app',
    iosBundleId: 'com.groupflow.groupflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI82E_0HdOz-EFgC05Ugj00tVgkY6nXr8',
    appId: '1:481730324850:ios:4914f9dce55945893ed5eb',
    messagingSenderId: '481730324850',
    projectId: 'groupflow-dd0d4',
    storageBucket: 'groupflow-dd0d4.firebasestorage.app',
    iosBundleId: 'com.groupflow.groupflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZL5IPcRK_I9mp45X1dbPkCXZnnA7K19E',
    appId: '1:481730324850:web:c87d719a62e554ef3ed5eb',
    messagingSenderId: '481730324850',
    projectId: 'groupflow-dd0d4',
    authDomain: 'groupflow-dd0d4.firebaseapp.com',
    storageBucket: 'groupflow-dd0d4.firebasestorage.app',
    measurementId: 'G-QN09JFZ9GZ',
  );
}
